import { Request, Response } from 'express';
import mongoose from 'mongoose';
import Order from '../models/Order';
import Product from '../models/Product';
import crypto from 'crypto';
import Razorpay from 'razorpay';
import logger from '../utils/logger';
import { AuthRequest } from '../middleware/authMiddleware';

const razorpay = new Razorpay({
  key_id: process.env.RAZORPAY_KEY_ID || '',
  key_secret: process.env.RAZORPAY_KEY_SECRET || '',
});

export const addOrderItems = async (req: AuthRequest, res: Response) => {
  const {
    orderItems,
    shippingAddress,
    paymentMethod,
    idempotencyKey, // Generated by frontend (e.g., hash of cart + timestamp)
  } = req.body;

  if (orderItems && orderItems.length === 0) {
    res.status(400).json({ message: 'No order items' });
    return;
  }

  try {
    // Idempotency check
    if (idempotencyKey && req.user) {
      const existingOrder = await Order.findOne({ user: req.user.id, idempotencyKey });
      if (existingOrder) {
        return res.status(200).json(existingOrder);
      }
    }

    let calculatedTotalPrice = 0;
    const verifiedOrderItems = [];

    for (const item of orderItems) {
      const dbProduct = await Product.findById(item.product);

      if (!dbProduct) {
        return res.status(404).json({ message: `Product ${item.product} not found` });
      }

      if (dbProduct.stock < item.quantity) {
        return res.status(400).json({ message: `Insufficient stock for ${dbProduct.name}` });
      }

      const itemPrice = dbProduct.price;
      calculatedTotalPrice += itemPrice * item.quantity;

      verifiedOrderItems.push({
        ...item,
        price: itemPrice,
        name: dbProduct.name,
        image: dbProduct.image,
        product: dbProduct._id
      });
    }

    // 1. Create Order in Pending State
    const order = new Order({
      orderItems: verifiedOrderItems,
      user: req.user?.id,
      shippingAddress,
      paymentMethod,
      totalPrice: calculatedTotalPrice,
      isPaid: false,
      idempotencyKey,
      status: 'PENDING'
    });

    // 2. If Razorpay, create Payment Intent
    if (paymentMethod === 'Razorpay') {
      const options = {
        amount: Math.round(calculatedTotalPrice * 100),
        currency: "INR",
        receipt: `receipt_order_${order._id}`,
      };

      const razorpayOrder = await razorpay.orders.create(options);
      order.razorpayOrderId = razorpayOrder.id;
    }

    const createdOrder = await order.save();
    res.status(201).json(createdOrder);
  } catch (error: any) {
    res.status(500).json({ message: 'Error creating order', error: error.message });
  }
};

export const verifyPayment = async (req: AuthRequest, res: Response) => {
  const { razorpay_order_id, razorpay_payment_id, razorpay_signature } = req.body;

  const secret = process.env.RAZORPAY_KEY_SECRET!;
  const hmac = crypto.createHmac('sha256', secret);
  hmac.update(razorpay_order_id + "|" + razorpay_payment_id);
  const generated_signature = hmac.digest('hex');

  if (generated_signature === razorpay_signature) {
    const session = await mongoose.startSession();
    session.startTransaction();

    try {
      const order = await Order.findOne({ razorpayOrderId: razorpay_order_id }).session(session);

      if (order && !order.isPaid) {
        order.isPaid = true;
        order.paidAt = new Date();
        order.status = 'PAID';
        order.paymentResult = {
          id: razorpay_payment_id,
          status: 'success',
          update_time: new Date().toISOString(),
          email_address: '',
        };

        // Decrease stock with safety check
        for (const item of order.orderItems) {
          const product = await Product.findOneAndUpdate(
            { _id: item.product, stock: { $gte: item.quantity } },
            { $inc: { stock: -item.quantity } },
            { session, new: true }
          );

          if (!product) {
            throw new Error(`Insufficient stock for product: ${item.name}`);
          }
        }

        await order.save({ session });
        await session.commitTransaction();
        res.json({ status: 'success', message: 'Payment verified' });
      } else {
        await session.abortTransaction();
        res.status(400).json({ message: 'Order already processed, not found, or payment failed' });
      }
    } catch (error: any) {
      await session.abortTransaction();
      logger.error(`[PAYMENT_ERROR] User: ${req.user?.id} Order: ${razorpay_order_id} Error: ${error.message}`);
      res.status(500).json({ message: error.message || 'Error processing payment' });
    } finally {
      session.endSession();
    }
  } else {
    logger.warn(`[SECURITY_ALERT] Invalid signature attempt for Order: ${razorpay_order_id}`);
    res.status(400).json({ status: 'failure', message: 'Invalid signature' });
  }
};

export const razorpayWebhook = async (req: any, res: Response) => {
  const webhookSecret = process.env.RAZORPAY_WEBHOOK_SECRET;
  if (!webhookSecret) {
    res.status(400).send('Webhook secret not configured');
    return;
  }
  const signature = req.headers['x-razorpay-signature'] as string;

  // SECURITY FIX: Use rawBody for signature verification
  const shasum = crypto.createHmac('sha256', webhookSecret);
  shasum.update(req.rawBody || JSON.stringify(req.body));
  const digest = shasum.digest('hex');

  if (signature === digest) {
    const event = req.body.event;
    if (event === 'payment.captured') {
      const { order_id, id: payment_id } = req.body.payload.payment.entity;

      const session = await mongoose.startSession();
      session.startTransaction();

      try {
        const order = await Order.findOne({ razorpayOrderId: order_id }).session(session);
        if (order && !order.isPaid) {
          order.isPaid = true;
          order.paidAt = new Date();
          order.status = 'PAID';
          order.paymentResult = {
            id: payment_id,
            status: 'captured',
            update_time: new Date().toISOString(),
            email_address: req.body.payload.payment.entity.email,
          };

          for (const item of order.orderItems) {
            const product = await Product.findOneAndUpdate(
              { _id: item.product, stock: { $gte: item.quantity } },
              { $inc: { stock: -item.quantity } },
              { session, new: true }
            );

            if (!product) {
              throw new Error(`Insufficient stock for product: ${item.name}`);
            }
          }
          await order.save({ session });
          await session.commitTransaction();
        } else {
          await session.abortTransaction();
        }
      } catch (error) {
        await session.abortTransaction();
        // Log webhook failure but respond 200 to prevent retry if logic failed
        logger.error('Webhook processing error:', error);
      } finally {
        session.endSession();
      }
    }
    res.status(200).send('OK');
  } else {
    res.status(400).send('Invalid Signature');
  }
};

export const getOrders = async (req: AuthRequest, res: Response) => {
  try {
    const orders = await Order.find({}).populate('user', 'id name');
    res.json(orders);
  } catch (error) {
    res.status(500).json({ message: 'Error fetching orders', error });
  }
};

export const updateOrderToDelivered = async (req: AuthRequest, res: Response) => {
  try {
    const order = await Order.findById(req.params.id);

    if (order) {
      order.isDelivered = true;
      order.deliveredAt = new Date();
      order.status = 'DELIVERED';

      const updatedOrder = await order.save();
      res.json(updatedOrder);
    } else {
      res.status(404).json({ message: 'Order not found' });
    }
  } catch (error) {
    res.status(500).json({ message: 'Error updating delivery status', error });
  }
};

export const getMyOrders = async (req: AuthRequest, res: Response) => {
  try {
    const orders = await Order.find({ user: req.user?.id });
    res.json(orders);
  } catch (error) {
    res.status(500).json({ message: 'Error fetching orders', error });
  }
};

export const getOrderById = async (req: AuthRequest, res: Response) => {
  try {
    const order = await Order.findById(req.params.id).populate('user', 'name email');

    if (!order) {
      return res.status(404).json({ message: 'Order not found' });
    }

    // Only allow the order owner or an admin to view it
    const userId = req.user?.id;
    const orderUser = order.user as any;
    const isOwner = orderUser && (orderUser._id ? orderUser._id.toString() : orderUser.toString()) === userId;
    const isAdmin = req.user?.role === 'admin';

    if (!isOwner && !isAdmin) {
      return res.status(403).json({ message: 'Not authorized to view this order' });
    }

    res.json(order);
  } catch (error) {
    res.status(500).json({ message: 'Error fetching order', error });
  }
};

// 10/10 LOGIC: Reconciliation Mechanism
// Syncs "PENDING" orders with Razorpay in case webhooks were missed
export const reconcileOrder = async (req: AuthRequest, res: Response) => {
  try {
    const order = await Order.findById(req.params.id);
    if (!order) return res.status(404).json({ message: 'Order not found' });
    if (order.isPaid) return res.json({ message: 'Order already paid', order });

    if (!order.razorpayOrderId) return res.status(400).json({ message: 'No payment intent for this order' });

    // Fetch actual status from Razorpay
    const rzpOrder: any = await razorpay.orders.fetch(order.razorpayOrderId);
    const payments: any = await razorpay.orders.fetchPayments(order.razorpayOrderId);

    const successfulPayment = payments.items.find((p: any) => p.status === 'captured');

    if (successfulPayment) {
      const session = await mongoose.startSession();
      session.startTransaction();
      try {
        order.isPaid = true;
        order.paidAt = new Date();
        order.status = 'PAID';
        order.paymentResult = {
          id: successfulPayment.id,
          status: 'captured',
          update_time: new Date().toISOString(),
          email_address: successfulPayment.email,
        };

        for (const item of order.orderItems) {
          await Product.findOneAndUpdate(
            { _id: item.product, stock: { $gte: item.quantity } },
            { $inc: { stock: -item.quantity } },
            { session }
          );
        }
        await order.save({ session });
        await session.commitTransaction();
        res.json({ message: 'Reconciliation successful: Order marked as PAID', order });
      } catch (err) {
        await session.abortTransaction();
        throw err;
      } finally {
        session.endSession();
      }
    } else {
      res.json({ message: 'Razorpay confirms order is still unpaid', rzpStatus: rzpOrder.status });
    }
  } catch (error: any) {
    res.status(500).json({ message: 'Reconciliation failed', error: error.message });
  }
};
